bin = {

    "AA Battery": {"Item":"Hazardous","Bin":"Red"},
    "AAA Battery": {"Item":"Hazardous","Bin":"Red"},
    "AC Remote": {"Item":"E-Waste","Bin":"Red"},
    "Acid Bottle": {"Item":"Hazardous","Bin":"Red"},
    "Adult Diaper": {"Item":"Sanitary","Bin":"Red"},
    "Aerosol Spray Can": {"Item":"Hazardous","Bin":"Red"},
    "Almond Shells": {"Item":"Organic","Bin":"Green"},
    "Aluminium Can": {"Item":"Dry","Bin":"Blue"},
    "Aluminium Foil Clean": {"Item":"Dry","Bin":"Blue"},
    "Aluminium Pan": {"Item":"Dry","Bin":"Blue"},
    "Aluminium Pot": {"Item":"Dry","Bin":"Blue"},
    "Aluminium Vessel": {"Item":"Dry","Bin":"Blue"},
    "Amazon Box": {"Item":"Dry","Bin":"Blue"},
    "Amla Peel": {"Item":"Organic","Bin":"Green"},
    "Amla Seeds": {"Item":"Organic","Bin":"Green"},
    "Answer Sheet": {"Item":"Dry","Bin":"Blue"},
    "Appam Batter Waste": {"Item":"Organic","Bin":"Green"},
    "Apple Core": {"Item":"Organic","Bin":"Green"},
    "Areca Nut Shell": {"Item":"Organic","Bin":"Green"},
    "Baby Diaper": {"Item":"Sanitary","Bin":"Red"},
    "Baby Wipes": {"Item":"Sanitary","Bin":"Red"},
    "Backpack": {"Item":"Dry","Bin":"Blue"},
    "Bakery Food Waste": {"Item":"Organic","Bin":"Green"},
    "Banana": {"Item":"Organic","Bin":"Green"},
    "Banana Flower": {"Item":"Organic","Bin":"Green"},
    "Banana Peel": {"Item":"Organic","Bin":"Green"},
    "Banana Stem": {"Item":"Organic","Bin":"Green"},
    "Bandage": {"Item":"Sanitary","Bin":"Red"},
    "Barfi Waste": {"Item":"Organic","Bin":"Green"},
    "Basil Leaves": {"Item":"Organic","Bin":"Green"},
    "Bay Leaves": {"Item":"Organic","Bin":"Green"},
    "Bean Sprout Roots": {"Item":"Organic","Bin":"Green"},
    "Beans Ends": {"Item":"Organic","Bin":"Green"},
    "Bedsheet": {"Item":"Dry","Bin":"Blue"},
    "Beer Bottle": {"Item":"Dry","Bin":"Blue"},
    "Beer Can": {"Item":"Dry","Bin":"Blue"},
    "Beetroot Peels": {"Item":"Organic","Bin":"Green"},
    "Bike Battery": {"Item":"Hazardous","Bin":"Red"},
    "Biodegradable Food Waste": {"Item":"Organic","Bin":"Green"},
    "Biodegradable Kitchen Waste": {"Item":"Organic","Bin":"Green"},
    "Biryani Waste": {"Item":"Organic","Bin":"Green"},
    "Biscuit Wrapper": {"Item":"Dry","Bin":"Blue"},
    "Bitter Gourd Peels": {"Item":"Organic","Bin":"Green"},
    "Black Tea Leaves": {"Item":"Organic","Bin":"Green"},
    "Bleach Bottle": {"Item":"Hazardous","Bin":"Red"},
    "Blood Pressure Monitor": {"Item":"E-Waste","Bin":"Red"},
    "Blood Test Strip": {"Item":"Hazardous","Bin":"Red"},
    "Blood-Stained Cloth": {"Item":"Sanitary","Bin":"Red"},
    "Blood-Stained Cotton": {"Item":"Sanitary","Bin":"Red"},
    "Bluetooth Earbuds": {"Item":"E-Waste","Bin":"Red"},
    "Board Game Pieces": {"Item":"Dry","Bin":"Blue"},
    "Boiled Milk Skin": {"Item":"Organic","Bin":"Green"},
    "Bottle Gourd Peels": {"Item":"Organic","Bin":"Green"},
    "Bread Waste": {"Item":"Organic","Bin":"Green"},
    "Broken Blade": {"Item":"Hazardous","Bin":"Red"},
    "Broken Bulb": {"Item":"Hazardous","Bin":"Red"},
    "Broken Charger Pin": {"Item":"E-Waste","Bin":"Red"},
    "Broken Glass Clean": {"Item":"Dry","Bin":"Blue"},
    "Broken Keyboard": {"Item":"E-Waste","Bin":"Red"},
    "Broken Laptop": {"Item":"E-Waste","Bin":"Red"},
    "Broken Mouse": {"Item":"E-Waste","Bin":"Red"},
    "Broken PCB Piece": {"Item":"E-Waste","Bin":"Red"},
    "Broken Phone": {"Item":"E-Waste","Bin":"Red"},
    "Broken Rice": {"Item":"Organic","Bin":"Green"},
    "Broken Thermometer Mercury": {"Item":"Hazardous","Bin":"Red"},
    "Broken Tube Light": {"Item":"Hazardous","Bin":"Red"},
    "Brown Paper": {"Item":"Dry","Bin":"Blue"},
    "Bubble Wrap": {"Item":"Dry","Bin":"Blue"},
    "Burger Waste": {"Item":"Organic","Bin":"Green"},
    "Burnt Electronic Component": {"Item":"E-Waste","Bin":"Red"},
    "Burnt Food Scraps": {"Item":"Organic","Bin":"Green"},
    "Butter Residue": {"Item":"Organic","Bin":"Green"},
    "Buttermilk Waste": {"Item":"Organic","Bin":"Green"},
    "Button Cell": {"Item":"Hazardous","Bin":"Red"},
    "Cabbage Leaves": {"Item":"Organic","Bin":"Green"},
    "Calculator": {"Item":"E-Waste","Bin":"Red"},
    "Calendar": {"Item":"Dry","Bin":"Blue"},
    "Camera Battery": {"Item":"Hazardous","Bin":"Red"},
    "Car Battery": {"Item":"Hazardous","Bin":"Red"},
    "Cardboard Box": {"Item":"Dry","Bin":"Blue"},
    "Cardboard Tube": {"Item":"Dry","Bin":"Blue"},
    "Carrot Peels": {"Item":"Organic","Bin":"Green"},
    "Cashew Shells": {"Item":"Organic","Bin":"Green"},
    "Cauliflower Stems": {"Item":"Organic","Bin":"Green"},
    "CD": {"Item":"Dry","Bin":"Blue"},
    "CD Case": {"Item":"Dry","Bin":"Blue"},
    "Cereal Box": {"Item":"Dry","Bin":"Blue"},
    "CFL Bulb": {"Item":"Hazardous","Bin":"Red"},
    "Chapati Waste": {"Item":"Organic","Bin":"Green"},
    "Charging Cable": {"Item":"E-Waste","Bin":"Red"},
    "Chart Paper": {"Item":"Dry","Bin":"Blue"},
    "Cheese Scraps": {"Item":"Organic","Bin":"Green"},
    "Chemical Cleaner": {"Item":"Hazardous","Bin":"Red"},
    "Cherry Pits": {"Item":"Organic","Bin":"Green"},
    "Chicken Bones": {"Item":"Organic","Bin":"Green"},
    "Chicken Skin": {"Item":"Organic","Bin":"Green"},
    "Chips Packet": {"Item":"Dry","Bin":"Blue"},
    "Chocolate Crumbs": {"Item":"Organic","Bin":"Green"},
    "Chocolate Wrapper": {"Item":"Dry","Bin":"Blue"},
    "Circuit Board": {"Item":"E-Waste","Bin":"Red"},
    "Cloth Bag": {"Item":"Dry","Bin":"Blue"},
    "Coconut Husk": {"Item":"Organic","Bin":"Green"},
    "Coconut Shell": {"Item":"Organic","Bin":"Green"},
    "Coffee Grounds": {"Item":"Organic","Bin":"Green"},
    "Cold Drink Bottle": {"Item":"Dry","Bin":"Blue"},
    "Cold Drink Can": {"Item":"Dry","Bin":"Blue"},
    "Comic Book": {"Item":"Dry","Bin":"Blue"},
    "Compost Rejects": {"Item":"Organic","Bin":"Green"},
    "Computer Monitor": {"Item":"E-Waste","Bin":"Red"},
    "Conditioner Bottle": {"Item":"Dry","Bin":"Blue"},
    "Contact Lens": {"Item":"Sanitary","Bin":"Red"},
    "Contact Lens Case": {"Item":"Sanitary","Bin":"Red"},
    "Contaminated Plastic Waste": {"Item":"Hazardous","Bin":"Red"},
    "Cooked Dal": {"Item":"Organic","Bin":"Green"},
    "Cooked Fruit Waste": {"Item":"Organic","Bin":"Green"},
    "Cooked Lentils": {"Item":"Organic","Bin":"Green"},
    "Cooked Rice": {"Item":"Organic","Bin":"Green"},
    "Cooked Vegetables": {"Item":"Organic","Bin":"Green"},
    "Cooking Oil Residue": {"Item":"Organic","Bin":"Green"},
    "Cookware Lid": {"Item":"Dry","Bin":"Blue"},
    "Coriander Stems": {"Item":"Organic","Bin":"Green"},
    "Corn Cob": {"Item":"Organic","Bin":"Green"},
    "Corrugated Box": {"Item":"Dry","Bin":"Blue"},
    "Cosmetic Applicator Used": {"Item":"Sanitary","Bin":"Red"},
    "Cosmetic Box": {"Item":"Dry","Bin":"Blue"},
    "Cosmetic Glass Jar": {"Item":"Dry","Bin":"Blue"},
    "Cotton Cloth": {"Item":"Dry","Bin":"Blue"},
    "Cotton Pad Used": {"Item":"Sanitary","Bin":"Red"},
    "Cough Syrup Bottle": {"Item":"Hazardous","Bin":"Red"},
    "Courier Envelope": {"Item":"Dry","Bin":"Blue"},
    "Courier Plastic Cover": {"Item":"Dry","Bin":"Blue"},
    "COVID Test Kit": {"Item":"Hazardous","Bin":"Red"},
    "Crab Shells": {"Item":"Organic","Bin":"Green"},
    "Cucumber Peels": {"Item":"Organic","Bin":"Green"},
    "Curd Waste": {"Item":"Organic","Bin":"Green"},
    "Curry Leaves": {"Item":"Organic","Bin":"Green"},
    "Curtains": {"Item":"Dry","Bin":"Blue"},
    "Custard Apple Peel": {"Item":"Organic","Bin":"Green"},
    "Daily Wet Waste": {"Item":"Organic","Bin":"Green"},
    "Dal Water Residue": {"Item":"Organic","Bin":"Green"},
    "Damaged Power Strip": {"Item":"E-Waste","Bin":"Red"},
    "Denim Fabric": {"Item":"Dry","Bin":"Blue"},
    "Desktop CPU": {"Item":"E-Waste","Bin":"Red"},
    "Detergent Bottle": {"Item":"Dry","Bin":"Blue"},
    "Diaper": {"Item":"Sanitary","Bin":"Red"},
    "Diary": {"Item":"Dry","Bin":"Blue"},
    "Digital Clock": {"Item":"E-Waste","Bin":"Red"},
    "Digital Thermometer": {"Item":"Hazardous","Bin":"Red"},
    "Dinner Waste": {"Item":"Organic","Bin":"Green"},
    "Dishwash Liquid Bottle": {"Item":"Dry","Bin":"Blue"},
    "Disposable Bowl": {"Item":"Dry","Bin":"Blue"},
    "Disposable Glass": {"Item":"Dry","Bin":"Blue"},
    "Disposable Plate": {"Item":"Dry","Bin":"Blue"},
    "Disposable Razor": {"Item":"Hazardous","Bin":"Red"},
    "Dosa Batter Waste": {"Item":"Organic","Bin":"Green"},
    "Dosa Waste": {"Item":"Organic","Bin":"Green"},
    "Dough Waste": {"Item":"Organic","Bin":"Green"},
    "Drain Cleaner": {"Item":"Hazardous","Bin":"Red"},
    "Drawing Paper": {"Item":"Dry","Bin":"Blue"},
    "Drip Set": {"Item":"Hazardous","Bin":"Red"},
    "Drumstick Waste": {"Item":"Organic","Bin":"Green"},
    "Dry Leaves": {"Item":"Organic","Bin":"Green"},
    "Dry Plant Soil": {"Item":"Organic","Bin":"Green"},
    "DVD": {"Item":"Dry","Bin":"Blue"},
    "DVD Case": {"Item":"Dry","Bin":"Blue"},
    "Ear Bud Used": {"Item":"Sanitary","Bin":"Red"},
    "Earphones": {"Item":"E-Waste","Bin":"Red"},
    "Egg Carton": {"Item":"Dry","Bin":"Blue"},
    "Egg Shells": {"Item":"Organic","Bin":"Green"},
    "Electric Drill": {"Item":"E-Waste","Bin":"Red"},
    "Electric Shaver": {"Item":"E-Waste","Bin":"Red"},
    "Electric Socket": {"Item":"E-Waste","Bin":"Red"},
    "Electric Switch": {"Item":"E-Waste","Bin":"Red"},
    "Electric Toothbrush": {"Item":"E-Waste","Bin":"Red"},
    "Electric Trimmer": {"Item":"E-Waste","Bin":"Red"},
    "Electric Wire": {"Item":"E-Waste","Bin":"Red"},
    "Electronic Scrap": {"Item":"E-Waste","Bin":"Red"},
    "Electronic Wire Scrap": {"Item":"E-Waste","Bin":"Red"},
    "Electronics Packaging": {"Item":"Dry","Bin":"Blue"},
    "Exam Paper": {"Item":"Dry","Bin":"Blue"},
    "Expired Cooked Food": {"Item":"Organic","Bin":"Green"},
    "Expired Medicine": {"Item":"Hazardous","Bin":"Red"},
    "Expired Ointment": {"Item":"Hazardous","Bin":"Red"},
    "Expired Syrup": {"Item":"Hazardous","Bin":"Red"},
    "Extension Cord": {"Item":"E-Waste","Bin":"Red"},
    "Face Mask Used": {"Item":"Sanitary","Bin":"Red"},
    "Fallen Leaves": {"Item":"Organic","Bin":"Green"},
    "Feature Phone": {"Item":"E-Waste","Bin":"Red"},
    "Fenugreek Stems": {"Item":"Organic","Bin":"Green"},
    "Fermented Batter": {"Item":"Organic","Bin":"Green"},
    "Fermented Food Waste": {"Item":"Organic","Bin":"Green"},
    "Filter Coffee Waste": {"Item":"Organic","Bin":"Green"},
    "Firecracker Waste": {"Item":"Hazardous","Bin":"Red"},
    "Firework Residue": {"Item":"Hazardous","Bin":"Red"},
    "Fish Bones": {"Item":"Organic","Bin":"Green"},
    "Fish Scales": {"Item":"Organic","Bin":"Green"},
    "Flipkart Box": {"Item":"Dry","Bin":"Blue"},
    "Floor Cleaner Bottle": {"Item":"Dry","Bin":"Blue"},
    "Floor Cleaner Concentrate": {"Item":"Hazardous","Bin":"Red"},
    "Flour Residue": {"Item":"Organic","Bin":"Green"},
    "Flower Waste": {"Item":"Organic","Bin":"Green"},
    "Foam Packaging": {"Item":"Dry","Bin":"Blue"},
    "Food Packet Wrapper": {"Item":"Dry","Bin":"Blue"},
    "Food Scraps": {"Item":"Organic","Bin":"Green"},
    "Food Storage Box": {"Item":"Dry","Bin":"Blue"},
    "Food Tin": {"Item":"Dry","Bin":"Blue"},
    "Footwear": {"Item":"Dry","Bin":"Blue"},
    "Fresh Leaves": {"Item":"Organic","Bin":"Green"},
    "Frozen Food Packet": {"Item":"Dry","Bin":"Blue"},
    "Fruit Juice Residue": {"Item":"Organic","Bin":"Green"},
    "Fruit Pulp Waste": {"Item":"Organic","Bin":"Green"},
    "Fruit Salad Waste": {"Item":"Organic","Bin":"Green"},
    "Fused Bulb": {"Item":"Hazardous","Bin":"Red"},
    "Garbage Bag Clean": {"Item":"Dry","Bin":"Blue"},
    "Garden Weeds": {"Item":"Organic","Bin":"Green"},
    "Garland Flowers": {"Item":"Organic","Bin":"Green"},
    "Garlic Skins": {"Item":"Organic","Bin":"Green"},
    "Gas Lighter": {"Item":"Hazardous","Bin":"Red"},
    "Gauze": {"Item":"Sanitary","Bin":"Red"},
    "Ghee Residue": {"Item":"Organic","Bin":"Green"},
    "Gift Box": {"Item":"Dry","Bin":"Blue"},
    "Gift Wrapping Paper": {"Item":"Dry","Bin":"Blue"},
    "Ginger Peels": {"Item":"Organic","Bin":"Green"},
    "Glass Bottle": {"Item":"Dry","Bin":"Blue"},
    "Glass Bowl": {"Item":"Dry","Bin":"Blue"},
    "Glass Container": {"Item":"Dry","Bin":"Blue"},
    "Glass Jar": {"Item":"Dry","Bin":"Blue"},
    "Glass Paperweight": {"Item":"Dry","Bin":"Blue"},
    "Glass Plate": {"Item":"Dry","Bin":"Blue"},
    "Glass Showpiece": {"Item":"Dry","Bin":"Blue"},
    "Glass Tumbler": {"Item":"Dry","Bin":"Blue"},
    "Glass Vase": {"Item":"Dry","Bin":"Blue"},
    "Gloves Used": {"Item":"Sanitary","Bin":"Red"},
    "Glucometer Device": {"Item":"E-Waste","Bin":"Red"},
    "Grapes Stems": {"Item":"Organic","Bin":"Green"},
    "Grass Clippings": {"Item":"Organic","Bin":"Green"},
    "Gravy Waste": {"Item":"Organic","Bin":"Green"},
    "Grease Container": {"Item":"Hazardous","Bin":"Red"},
    "Green Tea Leaves": {"Item":"Organic","Bin":"Green"},
    "Greeting Card": {"Item":"Dry","Bin":"Blue"},
    "Guava Peel": {"Item":"Organic","Bin":"Green"},
    "Hair Dryer": {"Item":"E-Waste","Bin":"Red"},
    "Hair Dye Bottle": {"Item":"Hazardous","Bin":"Red"},
    "Hair Removal Blade": {"Item":"Hazardous","Bin":"Red"},
    "Hair Straightener": {"Item":"E-Waste","Bin":"Red"},
    "Halogen Bulb": {"Item":"Hazardous","Bin":"Red"},
    "Halwa Waste": {"Item":"Organic","Bin":"Green"},
    "Handbag": {"Item":"Dry","Bin":"Blue"},
    "Handwash Bottle": {"Item":"Dry","Bin":"Blue"},
    "Hardcover Book": {"Item":"Dry","Bin":"Blue"},
    "Headphones": {"Item":"E-Waste","Bin":"Red"},
    "Herbal Tea Waste": {"Item":"Organic","Bin":"Green"},
    "Highlighter Body": {"Item":"Dry","Bin":"Blue"},
    "Household Hazardous Waste": {"Item":"Hazardous","Bin":"Red"},
    "Household Organic Waste": {"Item":"Organic","Bin":"Green"},
    "Idli Batter Waste": {"Item":"Organic","Bin":"Green"},
    "Idli Waste": {"Item":"Organic","Bin":"Green"},
    "Inhaler": {"Item":"Hazardous","Bin":"Red"},
    "Injection Vial": {"Item":"Hazardous","Bin":"Red"},
    "Insecticide Spray": {"Item":"Hazardous","Bin":"Red"},
    "Instant Coffee Residue": {"Item":"Organic","Bin":"Green"},
    "Insulin Pen": {"Item":"Hazardous","Bin":"Red"},
    "Inverter": {"Item":"E-Waste","Bin":"Red"},
    "Inverter Battery": {"Item":"Hazardous","Bin":"Red"},
    "Invitation Card": {"Item":"Dry","Bin":"Blue"},
    "IV Tube": {"Item":"Hazardous","Bin":"Red"},
    "Jackfruit Fiber": {"Item":"Organic","Bin":"Green"},
    "Jackfruit Seeds": {"Item":"Organic","Bin":"Green"},
    "Jackfruit Waste": {"Item":"Organic","Bin":"Green"},
    "Jaggery Residue": {"Item":"Organic","Bin":"Green"},
    "Jalebi Waste": {"Item":"Organic","Bin":"Green"},
    "Jam Bottle": {"Item":"Dry","Bin":"Blue"},
    "Jewellery Box": {"Item":"Dry","Bin":"Blue"},
    "Juice Bottle": {"Item":"Dry","Bin":"Blue"},
    "Juicer Waste": {"Item":"Organic","Bin":"Green"},
    "Keyboard": {"Item":"E-Waste","Bin":"Red"},
    "Kheer Waste": {"Item":"Organic","Bin":"Green"},
    "Kitchen Compost Waste": {"Item":"Organic","Bin":"Green"},
    "Kitchen Waste": {"Item":"Organic","Bin":"Green"},
    "Kiwi Peel": {"Item":"Organic","Bin":"Green"},
    "Kokum Waste": {"Item":"Organic","Bin":"Green"},
    "Laddu Crumbs": {"Item":"Organic","Bin":"Green"},
    "Laptop Adapter": {"Item":"E-Waste","Bin":"Red"},
    "Laptop Battery": {"Item":"Hazardous","Bin":"Red"},
    "Laptop Box": {"Item":"Dry","Bin":"Blue"},
    "Laptop Charger": {"Item":"E-Waste","Bin":"Red"},
    "Laptop Motherboard": {"Item":"E-Waste","Bin":"Red"},
    "LCD Screen": {"Item":"E-Waste","Bin":"Red"},
    "Leather Belt": {"Item":"Dry","Bin":"Blue"},
    "Leather Wallet": {"Item":"Dry","Bin":"Blue"},
    "LED Bulb": {"Item":"Hazardous","Bin":"Red"},
    "LED Screen": {"Item":"E-Waste","Bin":"Red"},
    "Leftover Chutney": {"Item":"Organic","Bin":"Green"},
    "Leftover Dal": {"Item":"Organic","Bin":"Green"},
    "Leftover Dressing": {"Item":"Organic","Bin":"Green"},
    "Leftover Ketchup": {"Item":"Organic","Bin":"Green"},
    "Leftover Mayonnaise": {"Item":"Organic","Bin":"Green"},
    "Leftover Pickle": {"Item":"Organic","Bin":"Green"},
    "Leftover Rice": {"Item":"Organic","Bin":"Green"},
    "Leftover Sauce": {"Item":"Organic","Bin":"Green"},
    "Lemon Peel": {"Item":"Organic","Bin":"Green"},
    "Lemongrass Waste": {"Item":"Organic","Bin":"Green"},
    "Lime Peel": {"Item":"Organic","Bin":"Green"},
    "Lithium Battery": {"Item":"Hazardous","Bin":"Red"},
    "Lotus Stem Waste": {"Item":"Organic","Bin":"Green"},
    "Lubricant Spray": {"Item":"Hazardous","Bin":"Red"},
    "Luggage Bag": {"Item":"Dry","Bin":"Blue"},
    "Lunch Waste": {"Item":"Organic","Bin":"Green"},
    "Lychee Peel": {"Item":"Organic","Bin":"Green"},
    "Magazine": {"Item":"Dry","Bin":"Blue"},
    "Maize Husk": {"Item":"Organic","Bin":"Green"},
    "Makeup Sponge Used": {"Item":"Sanitary","Bin":"Red"},
    "Mango Peel": {"Item":"Organic","Bin":"Green"},
    "Marker Body": {"Item":"Dry","Bin":"Blue"},
    "Masala Tea Waste": {"Item":"Organic","Bin":"Green"},
    "Matchbox": {"Item":"Hazardous","Bin":"Red"},
    "Meal Leftovers": {"Item":"Organic","Bin":"Green"},
    "Meat Scraps": {"Item":"Organic","Bin":"Green"},
    "Medical Cotton": {"Item":"Sanitary","Bin":"Red"},
    "Medical Gloves": {"Item":"Hazardous","Bin":"Red"},
    "Medical Packaging Contaminated": {"Item":"Hazardous","Bin":"Red"},
    "Medicine Strip": {"Item":"Hazardous","Bin":"Red"},
    "Memory Card": {"Item":"E-Waste","Bin":"Red"},
    "Memory Card Case": {"Item":"Dry","Bin":"Blue"},
    "Metal Container": {"Item":"Dry","Bin":"Blue"},
    "Metal Flask": {"Item":"Dry","Bin":"Blue"},
    "Metal Jar": {"Item":"Dry","Bin":"Blue"},
    "Metal Lid": {"Item":"Dry","Bin":"Blue"},
    "Metal Lunch Box": {"Item":"Dry","Bin":"Blue"},
    "Metal Storage Tin": {"Item":"Dry","Bin":"Blue"},
    "Metal Water Bottle": {"Item":"Dry","Bin":"Blue"},
    "Milk Bottle": {"Item":"Dry","Bin":"Blue"},
    "Milk Cream": {"Item":"Organic","Bin":"Green"},
    "Milk Packet Clean": {"Item":"Dry","Bin":"Blue"},
    "Milk Residue": {"Item":"Organic","Bin":"Green"},
    "Milk Tea Residue": {"Item":"Organic","Bin":"Green"},
    "Mint Leaves": {"Item":"Organic","Bin":"Green"},
    "Mirror Small": {"Item":"Dry","Bin":"Blue"},
    "Mixed Organic Waste": {"Item":"Organic","Bin":"Green"},
    "Mobile Battery": {"Item":"Hazardous","Bin":"Red"},
    "Mobile Box": {"Item":"Dry","Bin":"Blue"},
    "Mobile Cover with Electronics": {"Item":"E-Waste","Bin":"Red"},
    "Mobile Phone": {"Item":"E-Waste","Bin":"Red"},
    "Modem": {"Item":"E-Waste","Bin":"Red"},
    "Modem Box": {"Item":"Dry","Bin":"Blue"},
    "Moldy Bread": {"Item":"Organic","Bin":"Green"},
    "Mosambi Peel": {"Item":"Organic","Bin":"Green"},
    "Mosquito Coil Ash": {"Item":"Hazardous","Bin":"Red"},
    "Mosquito Liquid Refill": {"Item":"Hazardous","Bin":"Red"},
    "Mosquito Repellent": {"Item":"Hazardous","Bin":"Red"},
    "Mouse": {"Item":"E-Waste","Bin":"Red"},
    "Muskmelon Peel": {"Item":"Organic","Bin":"Green"},
    "Mutton Bones": {"Item":"Organic","Bin":"Green"},
    "Nail Polish Bottle": {"Item":"Hazardous","Bin":"Red"},
    "Nail Polish Remover": {"Item":"Hazardous","Bin":"Red"},
    "Nebulizer": {"Item":"E-Waste","Bin":"Red"},
    "Nebulizer Mask": {"Item":"Hazardous","Bin":"Red"},
    "Needle": {"Item":"Hazardous","Bin":"Red"},
    "Newspaper": {"Item":"Dry","Bin":"Blue"},
    "Noodle Packet": {"Item":"Dry","Bin":"Blue"},
    "Noodles Waste": {"Item":"Organic","Bin":"Green"},
    "Notebook": {"Item":"Dry","Bin":"Blue"},
    "Notebook Cover": {"Item":"Dry","Bin":"Blue"},
    "Office Folder": {"Item":"Dry","Bin":"Blue"},
    "Office Paper": {"Item":"Dry","Bin":"Blue"},
    "Oil Bottle": {"Item":"Dry","Bin":"Blue"},
    "Oil Pouch Clean": {"Item":"Dry","Bin":"Blue"},
    "Oil-soaked Food Scraps": {"Item":"Organic","Bin":"Green"},
    "Old Books": {"Item":"Dry","Bin":"Blue"},
    "Old Clothes": {"Item":"Dry","Bin":"Blue"},
    "Old Laptop": {"Item":"E-Waste","Bin":"Red"},
    "Old Newspaper": {"Item":"Dry","Bin":"Blue"},
    "Onion Peels": {"Item":"Organic","Bin":"Green"},
    "Orange Peel": {"Item":"Organic","Bin":"Green"},
    "Orange Pith": {"Item":"Organic","Bin":"Green"},
    "Overcooked Food Waste": {"Item":"Organic","Bin":"Green"},
    "Overripe Fruits": {"Item":"Organic","Bin":"Green"},
    "Packaging Carton": {"Item":"Dry","Bin":"Blue"},
    "Packaging Plastic": {"Item":"Dry","Bin":"Blue"},
    "Paint Can": {"Item":"Hazardous","Bin":"Red"},
    "Paint Residue": {"Item":"Hazardous","Bin":"Red"},
    "Paint Thinner": {"Item":"Hazardous","Bin":"Red"},
    "Paneer Crumbs": {"Item":"Organic","Bin":"Green"},
    "Panty Liner": {"Item":"Sanitary","Bin":"Red"},
    "Papaya Peel": {"Item":"Organic","Bin":"Green"},
    "Paper": {"Item":"Dry","Bin":"Blue"},
    "Paper Bag": {"Item":"Dry","Bin":"Blue"},
    "Paper Envelope": {"Item":"Dry","Bin":"Blue"},
    "Paper File": {"Item":"Dry","Bin":"Blue"},
    "Paper Folder": {"Item":"Dry","Bin":"Blue"},
    "Paperback Book": {"Item":"Dry","Bin":"Blue"},
    "Pasta Waste": {"Item":"Organic","Bin":"Green"},
    "Payasam Waste": {"Item":"Organic","Bin":"Green"},
    "Peach Pit": {"Item":"Organic","Bin":"Green"},
    "Peanut Shells": {"Item":"Organic","Bin":"Green"},
    "Pear Core": {"Item":"Organic","Bin":"Green"},
    "Peas Pods": {"Item":"Organic","Bin":"Green"},
    "Pen Body": {"Item":"Dry","Bin":"Blue"},
    "Pen Drive": {"Item":"E-Waste","Bin":"Red"},
    "Perfume Bottle Empty": {"Item":"Dry","Bin":"Blue"},
    "Pesticide Bottle": {"Item":"Hazardous","Bin":"Red"},
    "Phenyl Bottle": {"Item":"Hazardous","Bin":"Red"},
    "Phone Charger": {"Item":"E-Waste","Bin":"Red"},
    "Pickle Jar": {"Item":"Dry","Bin":"Blue"},
    "Pickle Vegetable Waste": {"Item":"Organic","Bin":"Green"},
    "Pillow Cover": {"Item":"Dry","Bin":"Blue"},
    "Pineapple Peel": {"Item":"Organic","Bin":"Green"},
    "Pistachio Shells": {"Item":"Organic","Bin":"Green"},
    "Pizza Box Clean": {"Item":"Dry","Bin":"Blue"},
    "Pizza Crust": {"Item":"Organic","Bin":"Green"},
    "Plant Roots": {"Item":"Organic","Bin":"Green"},
    "Plant Trimmings": {"Item":"Organic","Bin":"Green"},
    "Plastic Basket": {"Item":"Dry","Bin":"Blue"},
    "Plastic Bottle": {"Item":"Dry","Bin":"Blue"},
    "Plastic Bucket": {"Item":"Dry","Bin":"Blue"},
    "Plastic Carry Bag": {"Item":"Dry","Bin":"Blue"},
    "Plastic Chair": {"Item":"Dry","Bin":"Blue"},
    "Plastic Container": {"Item":"Dry","Bin":"Blue"},
    "Plastic Cup": {"Item":"Dry","Bin":"Blue"},
    "Plastic Doll": {"Item":"Dry","Bin":"Blue"},
    "Plastic Dustbin": {"Item":"Dry","Bin":"Blue"},
    "Plastic Eraser Cover": {"Item":"Dry","Bin":"Blue"},
    "Plastic File": {"Item":"Dry","Bin":"Blue"},
    "Plastic Fork": {"Item":"Dry","Bin":"Blue"},
    "Plastic Hanger": {"Item":"Dry","Bin":"Blue"},
    "Plastic Jar": {"Item":"Dry","Bin":"Blue"},
    "Plastic Knife": {"Item":"Dry","Bin":"Blue"},
    "Plastic Lid": {"Item":"Dry","Bin":"Blue"},
    "Plastic Lunch Box": {"Item":"Dry","Bin":"Blue"},
    "Plastic Mug": {"Item":"Dry","Bin":"Blue"},
    "Plastic Plate": {"Item":"Dry","Bin":"Blue"},
    "Plastic Scale": {"Item":"Dry","Bin":"Blue"},
    "Plastic Sharpener": {"Item":"Dry","Bin":"Blue"},
    "Plastic Sheet": {"Item":"Dry","Bin":"Blue"},
    "Plastic Spoon": {"Item":"Dry","Bin":"Blue"},
    "Plastic Stool": {"Item":"Dry","Bin":"Blue"},
    "Plastic Storage Box": {"Item":"Dry","Bin":"Blue"},
    "Plastic Straw": {"Item":"Dry","Bin":"Blue"},
    "Plastic Table": {"Item":"Dry","Bin":"Blue"},
    "Plastic Toy": {"Item":"Dry","Bin":"Blue"},
    "Plastic Tub": {"Item":"Dry","Bin":"Blue"},
    "Plastic Wrapper Clean": {"Item":"Dry","Bin":"Blue"},
    "Plate Scraps": {"Item":"Organic","Bin":"Green"},
    "Plug Top": {"Item":"E-Waste","Bin":"Red"},
    "Plum Pit": {"Item":"Organic","Bin":"Green"},
    "Poha Waste": {"Item":"Organic","Bin":"Green"},
    "Pomegranate Peel": {"Item":"Organic","Bin":"Green"},
    "Potato Peels": {"Item":"Organic","Bin":"Green"},
    "Potted Plant Waste": {"Item":"Organic","Bin":"Green"},
    "Power Bank": {"Item":"E-Waste","Bin":"Red"},
    "Power Bank Battery": {"Item":"Hazardous","Bin":"Red"},
    "Prawn Shells": {"Item":"Organic","Bin":"Green"},
    "Pressure Cooker Body": {"Item":"Dry","Bin":"Blue"},
    "Printed Circuit Board": {"Item":"E-Waste","Bin":"Red"},
    "Printer Cartridge": {"Item":"E-Waste","Bin":"Red"},
    "Printer Paper": {"Item":"Dry","Bin":"Blue"},
    "Protective Plastic Film": {"Item":"Dry","Bin":"Blue"},
    "Pulao Waste": {"Item":"Organic","Bin":"Green"},
    "Pulse Oximeter": {"Item":"E-Waste","Bin":"Red"},
    "Pumpkin Peels": {"Item":"Organic","Bin":"Green"},
    "Purse": {"Item":"Dry","Bin":"Blue"},
    "Question Paper": {"Item":"Dry","Bin":"Blue"},
    "Radish Peels": {"Item":"Organic","Bin":"Green"},
    "Raw Mango Waste": {"Item":"Organic","Bin":"Green"},
    "Rechargeable Battery": {"Item":"Hazardous","Bin":"Red"},
    "Remote Control": {"Item":"E-Waste","Bin":"Red"},
    "Rice Water Residue": {"Item":"Organic","Bin":"Green"},
    "Ridge Gourd Peels": {"Item":"Organic","Bin":"Green"},
    "Room Freshener Can": {"Item":"Hazardous","Bin":"Red"},
    "Roti Crumbs": {"Item":"Organic","Bin":"Green"},
    "Router": {"Item":"E-Waste","Bin":"Red"},
    "Router Box": {"Item":"Dry","Bin":"Blue"},
    "Rubber Slippers": {"Item":"Dry","Bin":"Blue"},
    "Rug": {"Item":"Dry","Bin":"Blue"},
    "Rust Remover": {"Item":"Hazardous","Bin":"Red"},
    "Sandals": {"Item":"Dry","Bin":"Blue"},
    "Sandwich Waste": {"Item":"Organic","Bin":"Green"},
    "Sanitary Pad": {"Item":"Sanitary","Bin":"Red"},
    "Sauce Bottle": {"Item":"Dry","Bin":"Blue"},
    "Scanner": {"Item":"E-Waste","Bin":"Red"},
    "Seafood Waste": {"Item":"Organic","Bin":"Green"},
    "Set Top Box": {"Item":"E-Waste","Bin":"Red"},
    "Shampoo Bottle": {"Item":"Dry","Bin":"Blue"},
    "Sharp Metal Scrap": {"Item":"Hazardous","Bin":"Red"},
    "Sharp Object Waste": {"Item":"Hazardous","Bin":"Red"},
    "Shaving Blade": {"Item":"Hazardous","Bin":"Red"},
    "Shoe Box": {"Item":"Dry","Bin":"Blue"},
    "Shoe Packaging": {"Item":"Dry","Bin":"Blue"},
    "Shoes": {"Item":"Dry","Bin":"Blue"},
    "SIM Card": {"Item":"E-Waste","Bin":"Red"},
    "Small Twigs": {"Item":"Organic","Bin":"Green"},
    "Smartphone": {"Item":"E-Waste","Bin":"Red"},
    "Smoothie Pulp": {"Item":"Organic","Bin":"Green"},
    "Snack Packaging": {"Item":"Dry","Bin":"Blue"},
    "Soaked Lentils": {"Item":"Organic","Bin":"Green"},
    "Soaked Rice": {"Item":"Organic","Bin":"Green"},
    "Soap Bottle": {"Item":"Dry","Bin":"Blue"},
    "Soft Drink Bottle": {"Item":"Dry","Bin":"Blue"},
    "Soup Leftovers": {"Item":"Organic","Bin":"Green"},
    "Sour Milk": {"Item":"Organic","Bin":"Green"},
    "Spinach Stems": {"Item":"Organic","Bin":"Green"},
    "Spoiled Vegetables": {"Item":"Organic","Bin":"Green"},
    "Sprout Salad Waste": {"Item":"Organic","Bin":"Green"},
    "Sprouts Waste": {"Item":"Organic","Bin":"Green"},
    "Stabilizer": {"Item":"E-Waste","Bin":"Red"},
    "Stationery Box": {"Item":"Dry","Bin":"Blue"},
    "Stationery Plastic": {"Item":"Dry","Bin":"Blue"},
    "Steel Bowl": {"Item":"Dry","Bin":"Blue"},
    "Steel Box": {"Item":"Dry","Bin":"Blue"},
    "Steel Can": {"Item":"Dry","Bin":"Blue"},
    "Steel Container": {"Item":"Dry","Bin":"Blue"},
    "Steel Fork": {"Item":"Dry","Bin":"Blue"},
    "Steel Glass": {"Item":"Dry","Bin":"Blue"},
    "Steel Knife": {"Item":"Dry","Bin":"Blue"},
    "Steel Lid": {"Item":"Dry","Bin":"Blue"},
    "Steel Plate": {"Item":"Dry","Bin":"Blue"},
    "Steel Spoon": {"Item":"Dry","Bin":"Blue"},
    "Steel Tiffin Box": {"Item":"Dry","Bin":"Blue"},
    "Steel Tray": {"Item":"Dry","Bin":"Blue"},
    "Storage Carton": {"Item":"Dry","Bin":"Blue"},
    "Strawberry Tops": {"Item":"Organic","Bin":"Green"},
    "Stretch Film": {"Item":"Dry","Bin":"Blue"},
    "Sugar Syrup Residue": {"Item":"Organic","Bin":"Green"},
    "Sugarcane Bagasse": {"Item":"Organic","Bin":"Green"},
    "Sugarcane Waste": {"Item":"Organic","Bin":"Green"},
    "Surgical Mask": {"Item":"Sanitary","Bin":"Red"},
    "Sweet Lime Waste": {"Item":"Organic","Bin":"Green"},
    "Sweet Syrup Waste": {"Item":"Organic","Bin":"Green"},
    "Sweet Waste": {"Item":"Organic","Bin":"Green"},
    "Syringe": {"Item":"Hazardous","Bin":"Red"},
    "Tablet Blister Pack": {"Item":"Hazardous","Bin":"Red"},
    "Tamarind Pulp": {"Item":"Organic","Bin":"Green"},
    "Tamarind Seeds": {"Item":"Organic","Bin":"Green"},
    "Tampon": {"Item":"Sanitary","Bin":"Red"},
    "Tea Leaves": {"Item":"Organic","Bin":"Green"},
    "Temple Flowers": {"Item":"Organic","Bin":"Green"},
    "Thermocol": {"Item":"Dry","Bin":"Blue"},
    "Thermometer": {"Item":"Hazardous","Bin":"Red"},
    "Tin Can": {"Item":"Dry","Bin":"Blue"},
    "Toilet Cleaner": {"Item":"Hazardous","Bin":"Red"},
    "Toilet Paper Waste": {"Item":"Sanitary","Bin":"Red"},
    "Toner Cartridge": {"Item":"E-Waste","Bin":"Red"},
    "Tool Battery": {"Item":"Hazardous","Bin":"Red"},
    "Toothbrush Cover": {"Item":"Dry","Bin":"Blue"},
    "Toothpaste Box": {"Item":"Dry","Bin":"Blue"},
    "Toothpaste Tube Clean": {"Item":"Dry","Bin":"Blue"},
    "Towel": {"Item":"Dry","Bin":"Blue"},
    "Toy Packaging": {"Item":"Dry","Bin":"Blue"},
    "Tube Light": {"Item":"Hazardous","Bin":"Red"},
    "TV Box": {"Item":"Dry","Bin":"Blue"},
    "TV Remote": {"Item":"E-Waste","Bin":"Red"},
    "Uncooked Dal Waste": {"Item":"Organic","Bin":"Green"},
    "Uncooked Rice Waste": {"Item":"Organic","Bin":"Green"},
    "Undercooked Food Waste": {"Item":"Organic","Bin":"Green"},
    "Upma Waste": {"Item":"Organic","Bin":"Green"},
    "UPS": {"Item":"E-Waste","Bin":"Red"},
    "USB Cable": {"Item":"E-Waste","Bin":"Red"},
    "Used Battery": {"Item":"Hazardous","Bin":"Red"},
    "Used Cotton Ball": {"Item":"Sanitary","Bin":"Red"},
    "Used Cotton Swab": {"Item":"Sanitary","Bin":"Red"},
    "Used Engine Oil Container": {"Item":"Hazardous","Bin":"Red"},
    "Used First Aid Kit": {"Item":"Hazardous","Bin":"Red"},
    "Used Frying Oil Residue": {"Item":"Organic","Bin":"Green"},
    "Used Glucometer Strip": {"Item":"Hazardous","Bin":"Red"},
    "Used Mosquito Coil": {"Item":"Hazardous","Bin":"Red"},
    "Used Napkin": {"Item":"Sanitary","Bin":"Red"},
    "Used Notebook": {"Item":"Dry","Bin":"Blue"},
    "Used Razor": {"Item":"Hazardous","Bin":"Red"},
    "Used Sanitary Pad": {"Item":"Sanitary","Bin":"Red"},
    "Used Syringe": {"Item":"Hazardous","Bin":"Red"},
    "Used Tea Bags": {"Item":"Organic","Bin":"Green"},
    "Used Test Tube": {"Item":"Hazardous","Bin":"Red"},
    "Used Tissue Paper": {"Item":"Sanitary","Bin":"Red"},
    "Vada Batter Waste": {"Item":"Organic","Bin":"Green"},
    "Vegetable Curry Waste": {"Item":"Organic","Bin":"Green"},
    "Vegetable Juice Residue": {"Item":"Organic","Bin":"Green"},
    "Vegetable Pulp": {"Item":"Organic","Bin":"Green"},
    "Vegetable Salad Waste": {"Item":"Organic","Bin":"Green"},
    "Vegetable Stock Waste": {"Item":"Organic","Bin":"Green"},
    "Vehicle Fuse": {"Item":"Hazardous","Bin":"Red"},
    "Visiting Card": {"Item":"Dry","Bin":"Blue"},
    "Walnut Shells": {"Item":"Organic","Bin":"Green"},
    "Water Bottle": {"Item":"Dry","Bin":"Blue"},
    "Watermelon Rind": {"Item":"Organic","Bin":"Green"},
    "Webcam": {"Item":"E-Waste","Bin":"Red"},
    "Wet Wipes": {"Item":"Sanitary","Bin":"Red"},
    "Wheat Grain Waste": {"Item":"Organic","Bin":"Green"},
    "WiFi Extender": {"Item":"E-Waste","Bin":"Red"},
    "Window Glass Piece": {"Item":"Dry","Bin":"Blue"},
    "Wine Bottle": {"Item":"Dry","Bin":"Blue"},
    "Woolen Clothes": {"Item":"Dry","Bin":"Blue"},

}
