bin = {

"Banana Peel": {"Item":"Organic","Bin":"Green"},
"Apple Core": {"Item":"Organic","Bin":"Green"},
"Orange Peel": {"Item":"Organic","Bin":"Green"},
"Mango Peel": {"Item":"Organic","Bin":"Green"},
"Papaya Peel": {"Item":"Organic","Bin":"Green"},
"Watermelon Rind": {"Item":"Organic","Bin":"Green"},
"Muskmelon Peel": {"Item":"Organic","Bin":"Green"},
"Pineapple Peel": {"Item":"Organic","Bin":"Green"},
"Guava Peel": {"Item":"Organic","Bin":"Green"},
"Pear Core": {"Item":"Organic","Bin":"Green"},
"Peach Pit": {"Item":"Organic","Bin":"Green"},
"Plum Pit": {"Item":"Organic","Bin":"Green"},
"Cherry Pits": {"Item":"Organic","Bin":"Green"},
"Grapes Stems": {"Item":"Organic","Bin":"Green"},
"Strawberry Tops": {"Item":"Organic","Bin":"Green"},
"Kiwi Peel": {"Item":"Organic","Bin":"Green"},
"Pomegranate Peel": {"Item":"Organic","Bin":"Green"},
"Custard Apple Peel": {"Item":"Organic","Bin":"Green"},
"Lychee Peel": {"Item":"Organic","Bin":"Green"},
"Jackfruit Waste": {"Item":"Organic","Bin":"Green"},

"Potato Peels": {"Item":"Organic","Bin":"Green"},
"Onion Peels": {"Item":"Organic","Bin":"Green"},
"Garlic Skins": {"Item":"Organic","Bin":"Green"},
"Ginger Peels": {"Item":"Organic","Bin":"Green"},
"Carrot Peels": {"Item":"Organic","Bin":"Green"},
"Beetroot Peels": {"Item":"Organic","Bin":"Green"},
"Radish Peels": {"Item":"Organic","Bin":"Green"},
"Cucumber Peels": {"Item":"Organic","Bin":"Green"},
"Bottle Gourd Peels": {"Item":"Organic","Bin":"Green"},
"Ridge Gourd Peels": {"Item":"Organic","Bin":"Green"},
"Bitter Gourd Peels": {"Item":"Organic","Bin":"Green"},
"Pumpkin Peels": {"Item":"Organic","Bin":"Green"},
"Drumstick Waste": {"Item":"Organic","Bin":"Green"},
"Beans Ends": {"Item":"Organic","Bin":"Green"},
"Peas Pods": {"Item":"Organic","Bin":"Green"},
"Cauliflower Stems": {"Item":"Organic","Bin":"Green"},
"Cabbage Leaves": {"Item":"Organic","Bin":"Green"},
"Spinach Stems": {"Item":"Organic","Bin":"Green"},
"Fenugreek Stems": {"Item":"Organic","Bin":"Green"},
"Coriander Stems": {"Item":"Organic","Bin":"Green"},

"Cooked Rice": {"Item":"Organic","Bin":"Green"},
"Leftover Rice": {"Item":"Organic","Bin":"Green"},
"Cooked Dal": {"Item":"Organic","Bin":"Green"},
"Leftover Dal": {"Item":"Organic","Bin":"Green"},
"Cooked Vegetables": {"Item":"Organic","Bin":"Green"},
"Vegetable Curry Waste": {"Item":"Organic","Bin":"Green"},
"Chapati Waste": {"Item":"Organic","Bin":"Green"},
"Roti Crumbs": {"Item":"Organic","Bin":"Green"},
"Bread Waste": {"Item":"Organic","Bin":"Green"},
"Idli Waste": {"Item":"Organic","Bin":"Green"},
"Dosa Waste": {"Item":"Organic","Bin":"Green"},
"Upma Waste": {"Item":"Organic","Bin":"Green"},
"Poha Waste": {"Item":"Organic","Bin":"Green"},
"Pulao Waste": {"Item":"Organic","Bin":"Green"},
"Biryani Waste": {"Item":"Organic","Bin":"Green"},
"Pasta Waste": {"Item":"Organic","Bin":"Green"},
"Noodles Waste": {"Item":"Organic","Bin":"Green"},
"Pizza Crust": {"Item":"Organic","Bin":"Green"},
"Sandwich Waste": {"Item":"Organic","Bin":"Green"},
"Burger Waste": {"Item":"Organic","Bin":"Green"},

"Tea Leaves": {"Item":"Organic","Bin":"Green"},
"Used Tea Bags": {"Item":"Organic","Bin":"Green"},
"Coffee Grounds": {"Item":"Organic","Bin":"Green"},
"Milk Residue": {"Item":"Organic","Bin":"Green"},
"Curd Waste": {"Item":"Organic","Bin":"Green"},
"Buttermilk Waste": {"Item":"Organic","Bin":"Green"},
"Paneer Crumbs": {"Item":"Organic","Bin":"Green"},
"Cheese Scraps": {"Item":"Organic","Bin":"Green"},
"Butter Residue": {"Item":"Organic","Bin":"Green"},
"Ghee Residue": {"Item":"Organic","Bin":"Green"},

"Egg Shells": {"Item":"Organic","Bin":"Green"},
"Fish Bones": {"Item":"Organic","Bin":"Green"},
"Fish Scales": {"Item":"Organic","Bin":"Green"},
"Chicken Bones": {"Item":"Organic","Bin":"Green"},
"Chicken Skin": {"Item":"Organic","Bin":"Green"},
"Mutton Bones": {"Item":"Organic","Bin":"Green"},
"Meat Scraps": {"Item":"Organic","Bin":"Green"},
"Prawn Shells": {"Item":"Organic","Bin":"Green"},
"Crab Shells": {"Item":"Organic","Bin":"Green"},
"Seafood Waste": {"Item":"Organic","Bin":"Green"},

"Flower Waste": {"Item":"Organic","Bin":"Green"},
"Temple Flowers": {"Item":"Organic","Bin":"Green"},
"Garland Flowers": {"Item":"Organic","Bin":"Green"},
"Dry Leaves": {"Item":"Organic","Bin":"Green"},
"Fresh Leaves": {"Item":"Organic","Bin":"Green"},
"Grass Clippings": {"Item":"Organic","Bin":"Green"},
"Garden Weeds": {"Item":"Organic","Bin":"Green"},
"Plant Trimmings": {"Item":"Organic","Bin":"Green"},
"Fallen Leaves": {"Item":"Organic","Bin":"Green"},
"Small Twigs": {"Item":"Organic","Bin":"Green"},

"Coconut Shell": {"Item":"Organic","Bin":"Green"},
"Coconut Husk": {"Item":"Organic","Bin":"Green"},
"Areca Nut Shell": {"Item":"Organic","Bin":"Green"},
"Peanut Shells": {"Item":"Organic","Bin":"Green"},
"Cashew Shells": {"Item":"Organic","Bin":"Green"},
"Walnut Shells": {"Item":"Organic","Bin":"Green"},
"Pistachio Shells": {"Item":"Organic","Bin":"Green"},
"Almond Shells": {"Item":"Organic","Bin":"Green"},
"Corn Cob": {"Item":"Organic","Bin":"Green"},
"Maize Husk": {"Item":"Organic","Bin":"Green"},

"Overripe Fruits": {"Item":"Organic","Bin":"Green"},
"Spoiled Vegetables": {"Item":"Organic","Bin":"Green"},
"Moldy Bread": {"Item":"Organic","Bin":"Green"},
"Expired Cooked Food": {"Item":"Organic","Bin":"Green"},
"Food Scraps": {"Item":"Organic","Bin":"Green"},
"Kitchen Waste": {"Item":"Organic","Bin":"Green"},
"Meal Leftovers": {"Item":"Organic","Bin":"Green"},
"Plate Scraps": {"Item":"Organic","Bin":"Green"},
"Lunch Waste": {"Item":"Organic","Bin":"Green"},
"Dinner Waste": {"Item":"Organic","Bin":"Green"},



"Fruit Pulp Waste": {"Item":"Organic","Bin":"Green"},
"Vegetable Pulp": {"Item":"Organic","Bin":"Green"},
"Juicer Waste": {"Item":"Organic","Bin":"Green"},
"Smoothie Pulp": {"Item":"Organic","Bin":"Green"},
"Fruit Juice Residue": {"Item":"Organic","Bin":"Green"},
"Vegetable Juice Residue": {"Item":"Organic","Bin":"Green"},
"Sugarcane Waste": {"Item":"Organic","Bin":"Green"},
"Sugarcane Bagasse": {"Item":"Organic","Bin":"Green"},
"Sugar Syrup Residue": {"Item":"Organic","Bin":"Green"},
"Jaggery Residue": {"Item":"Organic","Bin":"Green"},

"Rice Water Residue": {"Item":"Organic","Bin":"Green"},
"Dal Water Residue": {"Item":"Organic","Bin":"Green"},
"Vegetable Stock Waste": {"Item":"Organic","Bin":"Green"},
"Soup Leftovers": {"Item":"Organic","Bin":"Green"},
"Gravy Waste": {"Item":"Organic","Bin":"Green"},
"Curry Leaves": {"Item":"Organic","Bin":"Green"},
"Bay Leaves": {"Item":"Organic","Bin":"Green"},
"Mint Leaves": {"Item":"Organic","Bin":"Green"},
"Basil Leaves": {"Item":"Organic","Bin":"Green"},
"Lemongrass Waste": {"Item":"Organic","Bin":"Green"},

"Lemon Peel": {"Item":"Organic","Bin":"Green"},
"Lime Peel": {"Item":"Organic","Bin":"Green"},
"Orange Pith": {"Item":"Organic","Bin":"Green"},
"Mosambi Peel": {"Item":"Organic","Bin":"Green"},
"Sweet Lime Waste": {"Item":"Organic","Bin":"Green"},
"Tamarind Seeds": {"Item":"Organic","Bin":"Green"},
"Tamarind Pulp": {"Item":"Organic","Bin":"Green"},
"Kokum Waste": {"Item":"Organic","Bin":"Green"},
"Amla Peel": {"Item":"Organic","Bin":"Green"},
"Amla Seeds": {"Item":"Organic","Bin":"Green"},

"Banana Stem": {"Item":"Organic","Bin":"Green"},
"Banana Flower": {"Item":"Organic","Bin":"Green"},
"Lotus Stem Waste": {"Item":"Organic","Bin":"Green"},
"Jackfruit Seeds": {"Item":"Organic","Bin":"Green"},
"Jackfruit Fiber": {"Item":"Organic","Bin":"Green"},
"Raw Mango Waste": {"Item":"Organic","Bin":"Green"},
"Pickle Vegetable Waste": {"Item":"Organic","Bin":"Green"},
"Fermented Food Waste": {"Item":"Organic","Bin":"Green"},
"Sprouts Waste": {"Item":"Organic","Bin":"Green"},
"Bean Sprout Roots": {"Item":"Organic","Bin":"Green"},

"Cooked Lentils": {"Item":"Organic","Bin":"Green"},
"Soaked Lentils": {"Item":"Organic","Bin":"Green"},
"Soaked Rice": {"Item":"Organic","Bin":"Green"},
"Uncooked Rice Waste": {"Item":"Organic","Bin":"Green"},
"Uncooked Dal Waste": {"Item":"Organic","Bin":"Green"},
"Broken Rice": {"Item":"Organic","Bin":"Green"},
"Wheat Grain Waste": {"Item":"Organic","Bin":"Green"},
"Flour Residue": {"Item":"Organic","Bin":"Green"},
"Dough Waste": {"Item":"Organic","Bin":"Green"},
"Fermented Batter": {"Item":"Organic","Bin":"Green"},

"Idli Batter Waste": {"Item":"Organic","Bin":"Green"},
"Dosa Batter Waste": {"Item":"Organic","Bin":"Green"},
"Appam Batter Waste": {"Item":"Organic","Bin":"Green"},
"Vada Batter Waste": {"Item":"Organic","Bin":"Green"},
"Cooking Oil Residue": {"Item":"Organic","Bin":"Green"},
"Used Frying Oil Residue": {"Item":"Organic","Bin":"Green"},
"Oil-soaked Food Scraps": {"Item":"Organic","Bin":"Green"},
"Burnt Food Scraps": {"Item":"Organic","Bin":"Green"},
"Overcooked Food Waste": {"Item":"Organic","Bin":"Green"},
"Undercooked Food Waste": {"Item":"Organic","Bin":"Green"},

"Sweet Waste": {"Item":"Organic","Bin":"Green"},
"Halwa Waste": {"Item":"Organic","Bin":"Green"},
"Kheer Waste": {"Item":"Organic","Bin":"Green"},
"Payasam Waste": {"Item":"Organic","Bin":"Green"},
"Laddu Crumbs": {"Item":"Organic","Bin":"Green"},
"Jalebi Waste": {"Item":"Organic","Bin":"Green"},
"Barfi Waste": {"Item":"Organic","Bin":"Green"},
"Chocolate Crumbs": {"Item":"Organic","Bin":"Green"},
"Sweet Syrup Waste": {"Item":"Organic","Bin":"Green"},
"Bakery Food Waste": {"Item":"Organic","Bin":"Green"},

"Cooked Fruit Waste": {"Item":"Organic","Bin":"Green"},
"Fruit Salad Waste": {"Item":"Organic","Bin":"Green"},
"Vegetable Salad Waste": {"Item":"Organic","Bin":"Green"},
"Sprout Salad Waste": {"Item":"Organic","Bin":"Green"},
"Leftover Chutney": {"Item":"Organic","Bin":"Green"},
"Leftover Pickle": {"Item":"Organic","Bin":"Green"},
"Leftover Sauce": {"Item":"Organic","Bin":"Green"},
"Leftover Ketchup": {"Item":"Organic","Bin":"Green"},
"Leftover Mayonnaise": {"Item":"Organic","Bin":"Green"},
"Leftover Dressing": {"Item":"Organic","Bin":"Green"},

"Herbal Tea Waste": {"Item":"Organic","Bin":"Green"},
"Green Tea Leaves": {"Item":"Organic","Bin":"Green"},
"Black Tea Leaves": {"Item":"Organic","Bin":"Green"},
"Masala Tea Waste": {"Item":"Organic","Bin":"Green"},
"Filter Coffee Waste": {"Item":"Organic","Bin":"Green"},
"Instant Coffee Residue": {"Item":"Organic","Bin":"Green"},
"Milk Tea Residue": {"Item":"Organic","Bin":"Green"},
"Boiled Milk Skin": {"Item":"Organic","Bin":"Green"},
"Milk Cream": {"Item":"Organic","Bin":"Green"},
"Sour Milk": {"Item":"Organic","Bin":"Green"},

"Plant Roots": {"Item":"Organic","Bin":"Green"},
"Potted Plant Waste": {"Item":"Organic","Bin":"Green"},
"Dry Plant Soil": {"Item":"Organic","Bin":"Green"},
"Compost Rejects": {"Item":"Organic","Bin":"Green"},
"Biodegradable Food Waste": {"Item":"Organic","Bin":"Green"},
"Kitchen Compost Waste": {"Item":"Organic","Bin":"Green"},
"Household Organic Waste": {"Item":"Organic","Bin":"Green"},
"Daily Wet Waste": {"Item":"Organic","Bin":"Green"},
"Biodegradable Kitchen Waste": {"Item":"Organic","Bin":"Green"},
"Mixed Organic Waste": {"Item":"Organic","Bin":"Green"},

"Newspaper": {"Item":"Dry","Bin":"Blue"},
"Old Newspaper": {"Item":"Dry","Bin":"Blue"},
"Magazine": {"Item":"Dry","Bin":"Blue"},
"Comic Book": {"Item":"Dry","Bin":"Blue"},
"Notebook": {"Item":"Dry","Bin":"Blue"},
"Used Notebook": {"Item":"Dry","Bin":"Blue"},
"Office Paper": {"Item":"Dry","Bin":"Blue"},
"Printer Paper": {"Item":"Dry","Bin":"Blue"},
"Exam Paper": {"Item":"Dry","Bin":"Blue"},
"Question Paper": {"Item":"Dry","Bin":"Blue"},
"Answer Sheet": {"Item":"Dry","Bin":"Blue"},
"Drawing Paper": {"Item":"Dry","Bin":"Blue"},
"Chart Paper": {"Item":"Dry","Bin":"Blue"},
"Brown Paper": {"Item":"Dry","Bin":"Blue"},
"Paper Bag": {"Item":"Dry","Bin":"Blue"},
"Gift Wrapping Paper": {"Item":"Dry","Bin":"Blue"},
"Paper Envelope": {"Item":"Dry","Bin":"Blue"},
"Courier Envelope": {"Item":"Dry","Bin":"Blue"},
"Paper Folder": {"Item":"Dry","Bin":"Blue"},
"Old Books": {"Item":"Dry","Bin":"Blue"},

"Cardboard Box": {"Item":"Dry","Bin":"Blue"},
"Amazon Box": {"Item":"Dry","Bin":"Blue"},
"Flipkart Box": {"Item":"Dry","Bin":"Blue"},
"Shoe Box": {"Item":"Dry","Bin":"Blue"},
"Cereal Box": {"Item":"Dry","Bin":"Blue"},
"Pizza Box Clean": {"Item":"Dry","Bin":"Blue"},
"Packaging Carton": {"Item":"Dry","Bin":"Blue"},
"Egg Carton": {"Item":"Dry","Bin":"Blue"},
"Corrugated Box": {"Item":"Dry","Bin":"Blue"},
"Cardboard Tube": {"Item":"Dry","Bin":"Blue"},

"Plastic Bottle": {"Item":"Dry","Bin":"Blue"},
"Water Bottle": {"Item":"Dry","Bin":"Blue"},
"Soft Drink Bottle": {"Item":"Dry","Bin":"Blue"},
"Juice Bottle": {"Item":"Dry","Bin":"Blue"},
"Milk Bottle": {"Item":"Dry","Bin":"Blue"},
"Oil Bottle": {"Item":"Dry","Bin":"Blue"},
"Plastic Jar": {"Item":"Dry","Bin":"Blue"},
"Plastic Container": {"Item":"Dry","Bin":"Blue"},
"Food Storage Box": {"Item":"Dry","Bin":"Blue"},
"Plastic Lunch Box": {"Item":"Dry","Bin":"Blue"},

"Milk Packet Clean": {"Item":"Dry","Bin":"Blue"},
"Oil Pouch Clean": {"Item":"Dry","Bin":"Blue"},
"Plastic Wrapper Clean": {"Item":"Dry","Bin":"Blue"},
"Biscuit Wrapper": {"Item":"Dry","Bin":"Blue"},
"Chips Packet": {"Item":"Dry","Bin":"Blue"},
"Chocolate Wrapper": {"Item":"Dry","Bin":"Blue"},
"Noodle Packet": {"Item":"Dry","Bin":"Blue"},
"Frozen Food Packet": {"Item":"Dry","Bin":"Blue"},
"Snack Packaging": {"Item":"Dry","Bin":"Blue"},
"Food Packet Wrapper": {"Item":"Dry","Bin":"Blue"},

"Plastic Spoon": {"Item":"Dry","Bin":"Blue"},
"Plastic Fork": {"Item":"Dry","Bin":"Blue"},
"Plastic Knife": {"Item":"Dry","Bin":"Blue"},
"Plastic Plate": {"Item":"Dry","Bin":"Blue"},
"Plastic Cup": {"Item":"Dry","Bin":"Blue"},
"Disposable Glass": {"Item":"Dry","Bin":"Blue"},
"Disposable Plate": {"Item":"Dry","Bin":"Blue"},
"Disposable Bowl": {"Item":"Dry","Bin":"Blue"},
"Plastic Straw": {"Item":"Dry","Bin":"Blue"},
"Plastic Lid": {"Item":"Dry","Bin":"Blue"},

"Glass Bottle": {"Item":"Dry","Bin":"Blue"},
"Cold Drink Bottle": {"Item":"Dry","Bin":"Blue"},
"Beer Bottle": {"Item":"Dry","Bin":"Blue"},
"Wine Bottle": {"Item":"Dry","Bin":"Blue"},
"Glass Jar": {"Item":"Dry","Bin":"Blue"},
"Jam Bottle": {"Item":"Dry","Bin":"Blue"},
"Pickle Jar": {"Item":"Dry","Bin":"Blue"},
"Sauce Bottle": {"Item":"Dry","Bin":"Blue"},
"Perfume Bottle Empty": {"Item":"Dry","Bin":"Blue"},
"Cosmetic Glass Jar": {"Item":"Dry","Bin":"Blue"},

"Aluminium Can": {"Item":"Dry","Bin":"Blue"},
"Cold Drink Can": {"Item":"Dry","Bin":"Blue"},
"Beer Can": {"Item":"Dry","Bin":"Blue"},
"Tin Can": {"Item":"Dry","Bin":"Blue"},
"Food Tin": {"Item":"Dry","Bin":"Blue"},
"Steel Can": {"Item":"Dry","Bin":"Blue"},
"Metal Container": {"Item":"Dry","Bin":"Blue"},
"Steel Box": {"Item":"Dry","Bin":"Blue"},
"Metal Lid": {"Item":"Dry","Bin":"Blue"},
"Aluminium Foil Clean": {"Item":"Dry","Bin":"Blue"},

"Detergent Bottle": {"Item":"Dry","Bin":"Blue"},
"Shampoo Bottle": {"Item":"Dry","Bin":"Blue"},
"Conditioner Bottle": {"Item":"Dry","Bin":"Blue"},
"Soap Bottle": {"Item":"Dry","Bin":"Blue"},
"Handwash Bottle": {"Item":"Dry","Bin":"Blue"},
"Floor Cleaner Bottle": {"Item":"Dry","Bin":"Blue"},
"Dishwash Liquid Bottle": {"Item":"Dry","Bin":"Blue"},
"Toothpaste Tube Clean": {"Item":"Dry","Bin":"Blue"},
"Toothpaste Box": {"Item":"Dry","Bin":"Blue"},
"Toothbrush Cover": {"Item":"Dry","Bin":"Blue"},

"Stationery Plastic": {"Item":"Dry","Bin":"Blue"},
"Pen Body": {"Item":"Dry","Bin":"Blue"},
"Marker Body": {"Item":"Dry","Bin":"Blue"},
"Highlighter Body": {"Item":"Dry","Bin":"Blue"},
"Plastic Scale": {"Item":"Dry","Bin":"Blue"},
"Plastic Eraser Cover": {"Item":"Dry","Bin":"Blue"},
"Plastic Sharpener": {"Item":"Dry","Bin":"Blue"},
"CD Case": {"Item":"Dry","Bin":"Blue"},
"DVD Case": {"Item":"Dry","Bin":"Blue"},
"Plastic File": {"Item":"Dry","Bin":"Blue"},

"Bubble Wrap": {"Item":"Dry","Bin":"Blue"},
"Thermocol": {"Item":"Dry","Bin":"Blue"},
"Foam Packaging": {"Item":"Dry","Bin":"Blue"},
"Plastic Carry Bag": {"Item":"Dry","Bin":"Blue"},
"Garbage Bag Clean": {"Item":"Dry","Bin":"Blue"},
"Stretch Film": {"Item":"Dry","Bin":"Blue"},
"Plastic Sheet": {"Item":"Dry","Bin":"Blue"},
"Packaging Plastic": {"Item":"Dry","Bin":"Blue"},
"Courier Plastic Cover": {"Item":"Dry","Bin":"Blue"},
"Protective Plastic Film": {"Item":"Dry","Bin":"Blue"},
"Plastic Bucket": {"Item":"Dry","Bin":"Blue"},
"Plastic Mug": {"Item":"Dry","Bin":"Blue"},
"Plastic Tub": {"Item":"Dry","Bin":"Blue"},
"Plastic Storage Box": {"Item":"Dry","Bin":"Blue"},
"Plastic Basket": {"Item":"Dry","Bin":"Blue"},
"Plastic Dustbin": {"Item":"Dry","Bin":"Blue"},
"Plastic Stool": {"Item":"Dry","Bin":"Blue"},
"Plastic Chair": {"Item":"Dry","Bin":"Blue"},
"Plastic Table": {"Item":"Dry","Bin":"Blue"},
"Plastic Hanger": {"Item":"Dry","Bin":"Blue"},

"Steel Plate": {"Item":"Dry","Bin":"Blue"},
"Steel Spoon": {"Item":"Dry","Bin":"Blue"},
"Steel Fork": {"Item":"Dry","Bin":"Blue"},
"Steel Knife": {"Item":"Dry","Bin":"Blue"},
"Steel Bowl": {"Item":"Dry","Bin":"Blue"},
"Steel Glass": {"Item":"Dry","Bin":"Blue"},
"Steel Tiffin Box": {"Item":"Dry","Bin":"Blue"},
"Steel Container": {"Item":"Dry","Bin":"Blue"},
"Steel Tray": {"Item":"Dry","Bin":"Blue"},
"Steel Lid": {"Item":"Dry","Bin":"Blue"},

"Aluminium Vessel": {"Item":"Dry","Bin":"Blue"},
"Aluminium Pot": {"Item":"Dry","Bin":"Blue"},
"Aluminium Pan": {"Item":"Dry","Bin":"Blue"},
"Pressure Cooker Body": {"Item":"Dry","Bin":"Blue"},
"Cookware Lid": {"Item":"Dry","Bin":"Blue"},
"Metal Jar": {"Item":"Dry","Bin":"Blue"},
"Metal Storage Tin": {"Item":"Dry","Bin":"Blue"},
"Metal Lunch Box": {"Item":"Dry","Bin":"Blue"},
"Metal Water Bottle": {"Item":"Dry","Bin":"Blue"},
"Metal Flask": {"Item":"Dry","Bin":"Blue"},

"Glass Tumbler": {"Item":"Dry","Bin":"Blue"},
"Glass Bowl": {"Item":"Dry","Bin":"Blue"},
"Glass Plate": {"Item":"Dry","Bin":"Blue"},
"Broken Glass Clean": {"Item":"Dry","Bin":"Blue"},
"Glass Paperweight": {"Item":"Dry","Bin":"Blue"},
"Glass Vase": {"Item":"Dry","Bin":"Blue"},
"Glass Showpiece": {"Item":"Dry","Bin":"Blue"},
"Mirror Small": {"Item":"Dry","Bin":"Blue"},
"Window Glass Piece": {"Item":"Dry","Bin":"Blue"},
"Glass Container": {"Item":"Dry","Bin":"Blue"},

"Cloth Bag": {"Item":"Dry","Bin":"Blue"},
"Cotton Cloth": {"Item":"Dry","Bin":"Blue"},
"Old Clothes": {"Item":"Dry","Bin":"Blue"},
"Denim Fabric": {"Item":"Dry","Bin":"Blue"},
"Woolen Clothes": {"Item":"Dry","Bin":"Blue"},
"Bedsheet": {"Item":"Dry","Bin":"Blue"},
"Pillow Cover": {"Item":"Dry","Bin":"Blue"},
"Towel": {"Item":"Dry","Bin":"Blue"},
"Curtains": {"Item":"Dry","Bin":"Blue"},
"Rug": {"Item":"Dry","Bin":"Blue"},

"Footwear": {"Item":"Dry","Bin":"Blue"},
"Rubber Slippers": {"Item":"Dry","Bin":"Blue"},
"Shoes": {"Item":"Dry","Bin":"Blue"},
"Sandals": {"Item":"Dry","Bin":"Blue"},
"Leather Belt": {"Item":"Dry","Bin":"Blue"},
"Leather Wallet": {"Item":"Dry","Bin":"Blue"},
"Handbag": {"Item":"Dry","Bin":"Blue"},
"Backpack": {"Item":"Dry","Bin":"Blue"},
"Purse": {"Item":"Dry","Bin":"Blue"},
"Luggage Bag": {"Item":"Dry","Bin":"Blue"},

"CD": {"Item":"Dry","Bin":"Blue"},
"DVD": {"Item":"Dry","Bin":"Blue"},
"Pen Drive": {"Item":"Dry","Bin":"Blue"},
"Memory Card Case": {"Item":"Dry","Bin":"Blue"},
"Router Box": {"Item":"Dry","Bin":"Blue"},
"Modem Box": {"Item":"Dry","Bin":"Blue"},
"Electronics Packaging": {"Item":"Dry","Bin":"Blue"},
"Mobile Box": {"Item":"Dry","Bin":"Blue"},
"Laptop Box": {"Item":"Dry","Bin":"Blue"},
"TV Box": {"Item":"Dry","Bin":"Blue"},

"Calendar": {"Item":"Dry","Bin":"Blue"},
"Diary": {"Item":"Dry","Bin":"Blue"},
"Notebook Cover": {"Item":"Dry","Bin":"Blue"},
"Paperback Book": {"Item":"Dry","Bin":"Blue"},
"Hardcover Book": {"Item":"Dry","Bin":"Blue"},
"Greeting Card": {"Item":"Dry","Bin":"Blue"},
"Invitation Card": {"Item":"Dry","Bin":"Blue"},
"Visiting Card": {"Item":"Dry","Bin":"Blue"},
"Paper File": {"Item":"Dry","Bin":"Blue"},
"Office Folder": {"Item":"Dry","Bin":"Blue"},

"Plastic Toy": {"Item":"Dry","Bin":"Blue"},
"Board Game Pieces": {"Item":"Dry","Bin":"Blue"},
"Plastic Doll": {"Item":"Dry","Bin":"Blue"},
"Toy Packaging": {"Item":"Dry","Bin":"Blue"},
"Stationery Box": {"Item":"Dry","Bin":"Blue"},
"Cosmetic Box": {"Item":"Dry","Bin":"Blue"},
"Jewellery Box": {"Item":"Dry","Bin":"Blue"},
"Shoe Packaging": {"Item":"Dry","Bin":"Blue"},
"Gift Box": {"Item":"Dry","Bin":"Blue"},
"Storage Carton": {"Item":"Dry","Bin":"Blue"},

# ---------- BATTERIES ----------
"Used Battery": {"Item":"Hazardous","Bin":"Red"},
"AA Battery": {"Item":"Hazardous","Bin":"Red"},
"AAA Battery": {"Item":"Hazardous","Bin":"Red"},
"Button Cell": {"Item":"Hazardous","Bin":"Red"},
"Lithium Battery": {"Item":"Hazardous","Bin":"Red"},
"Rechargeable Battery": {"Item":"Hazardous","Bin":"Red"},
"Power Bank Battery": {"Item":"Hazardous","Bin":"Red"},
"Laptop Battery": {"Item":"Hazardous","Bin":"Red"},
"Mobile Battery": {"Item":"Hazardous","Bin":"Red"},
"Camera Battery": {"Item":"Hazardous","Bin":"Red"},

# ---------- E-WASTE : PHONES & ACCESSORIES ----------
"Mobile Phone": {"Item":"E-Waste","Bin":"Red"},
"Smartphone": {"Item":"E-Waste","Bin":"Red"},
"Feature Phone": {"Item":"E-Waste","Bin":"Red"},
"Broken Phone": {"Item":"E-Waste","Bin":"Red"},
"Phone Charger": {"Item":"E-Waste","Bin":"Red"},
"Charging Cable": {"Item":"E-Waste","Bin":"Red"},
"USB Cable": {"Item":"E-Waste","Bin":"Red"},
"Earphones": {"Item":"E-Waste","Bin":"Red"},
"Headphones": {"Item":"E-Waste","Bin":"Red"},
"Bluetooth Earbuds": {"Item":"E-Waste","Bin":"Red"},
"Power Bank": {"Item":"E-Waste","Bin":"Red"},
"Mobile Cover with Electronics": {"Item":"E-Waste","Bin":"Red"},
"SIM Card": {"Item":"E-Waste","Bin":"Red"},
"Memory Card": {"Item":"E-Waste","Bin":"Red"},
"Pen Drive": {"Item":"E-Waste","Bin":"Red"},

# ---------- E-WASTE : HOUSEHOLD ELECTRONICS ----------
"Remote Control": {"Item":"E-Waste","Bin":"Red"},
"TV Remote": {"Item":"E-Waste","Bin":"Red"},
"AC Remote": {"Item":"E-Waste","Bin":"Red"},
"Set Top Box": {"Item":"E-Waste","Bin":"Red"},
"Router": {"Item":"E-Waste","Bin":"Red"},
"Modem": {"Item":"E-Waste","Bin":"Red"},
"WiFi Extender": {"Item":"E-Waste","Bin":"Red"},
"Keyboard": {"Item":"E-Waste","Bin":"Red"},
"Mouse": {"Item":"E-Waste","Bin":"Red"},
"Webcam": {"Item":"E-Waste","Bin":"Red"},
"Printer Cartridge": {"Item":"E-Waste","Bin":"Red"},
"Toner Cartridge": {"Item":"E-Waste","Bin":"Red"},
"Scanner": {"Item":"E-Waste","Bin":"Red"},
"Calculator": {"Item":"E-Waste","Bin":"Red"},
"Digital Clock": {"Item":"E-Waste","Bin":"Red"},

# ---------- LIGHTING & ELECTRICAL ----------
"Broken Bulb": {"Item":"Hazardous","Bin":"Red"},
"LED Bulb": {"Item":"Hazardous","Bin":"Red"},
"CFL Bulb": {"Item":"Hazardous","Bin":"Red"},
"Tube Light": {"Item":"Hazardous","Bin":"Red"},
"Halogen Bulb": {"Item":"Hazardous","Bin":"Red"},
"Fused Bulb": {"Item":"Hazardous","Bin":"Red"},
"Broken Tube Light": {"Item":"Hazardous","Bin":"Red"},
"Electric Wire": {"Item":"E-Waste","Bin":"Red"},
"Extension Cord": {"Item":"E-Waste","Bin":"Red"},
"Plug Top": {"Item":"E-Waste","Bin":"Red"},

# ---------- SANITARY WASTE ----------
"Sanitary Pad": {"Item":"Sanitary","Bin":"Red"},
"Used Sanitary Pad": {"Item":"Sanitary","Bin":"Red"},
"Tampon": {"Item":"Sanitary","Bin":"Red"},
"Panty Liner": {"Item":"Sanitary","Bin":"Red"},
"Diaper": {"Item":"Sanitary","Bin":"Red"},
"Baby Diaper": {"Item":"Sanitary","Bin":"Red"},
"Adult Diaper": {"Item":"Sanitary","Bin":"Red"},
"Used Tissue Paper": {"Item":"Sanitary","Bin":"Red"},
"Used Napkin": {"Item":"Sanitary","Bin":"Red"},
"Toilet Paper Waste": {"Item":"Sanitary","Bin":"Red"},
"Baby Wipes": {"Item":"Sanitary","Bin":"Red"},
"Wet Wipes": {"Item":"Sanitary","Bin":"Red"},
"Cotton Pad Used": {"Item":"Sanitary","Bin":"Red"},
"Ear Bud Used": {"Item":"Sanitary","Bin":"Red"},
"Face Mask Used": {"Item":"Sanitary","Bin":"Red"},
"Surgical Mask": {"Item":"Sanitary","Bin":"Red"},
"Gloves Used": {"Item":"Sanitary","Bin":"Red"},
"Bandage": {"Item":"Sanitary","Bin":"Red"},
"Gauze": {"Item":"Sanitary","Bin":"Red"},
"Medical Cotton": {"Item":"Sanitary","Bin":"Red"},

# ---------- MEDICAL & PHARMACEUTICAL ----------
"Syringe": {"Item":"Hazardous","Bin":"Red"},
"Used Syringe": {"Item":"Hazardous","Bin":"Red"},
"Needle": {"Item":"Hazardous","Bin":"Red"},
"Injection Vial": {"Item":"Hazardous","Bin":"Red"},
"Expired Medicine": {"Item":"Hazardous","Bin":"Red"},
"Medicine Strip": {"Item":"Hazardous","Bin":"Red"},
"Tablet Blister Pack": {"Item":"Hazardous","Bin":"Red"},
"Cough Syrup Bottle": {"Item":"Hazardous","Bin":"Red"},
"Inhaler": {"Item":"Hazardous","Bin":"Red"},
"Thermometer": {"Item":"Hazardous","Bin":"Red"},
"Digital Thermometer": {"Item":"Hazardous","Bin":"Red"},
"Medical Gloves": {"Item":"Hazardous","Bin":"Red"},
"COVID Test Kit": {"Item":"Hazardous","Bin":"Red"},
"Insulin Pen": {"Item":"Hazardous","Bin":"Red"},
"Blood Test Strip": {"Item":"Hazardous","Bin":"Red"},

# ---------- CHEMICALS & TOXIC ----------
"Paint Can": {"Item":"Hazardous","Bin":"Red"},
"Paint Residue": {"Item":"Hazardous","Bin":"Red"},
"Nail Polish Bottle": {"Item":"Hazardous","Bin":"Red"},
"Nail Polish Remover": {"Item":"Hazardous","Bin":"Red"},
"Hair Dye Bottle": {"Item":"Hazardous","Bin":"Red"},
"Pesticide Bottle": {"Item":"Hazardous","Bin":"Red"},
"Insecticide Spray": {"Item":"Hazardous","Bin":"Red"},
"Mosquito Repellent": {"Item":"Hazardous","Bin":"Red"},
"Phenyl Bottle": {"Item":"Hazardous","Bin":"Red"},
"Bleach Bottle": {"Item":"Hazardous","Bin":"Red"},
"Drain Cleaner": {"Item":"Hazardous","Bin":"Red"},
"Toilet Cleaner": {"Item":"Hazardous","Bin":"Red"},
"Floor Cleaner Concentrate": {"Item":"Hazardous","Bin":"Red"},
"Acid Bottle": {"Item":"Hazardous","Bin":"Red"},
"Chemical Cleaner": {"Item":"Hazardous","Bin":"Red"},

# ---------- ADDITIONAL E-WASTE ----------
"Broken Laptop": {"Item":"E-Waste","Bin":"Red"},
"Old Laptop": {"Item":"E-Waste","Bin":"Red"},
"Laptop Charger": {"Item":"E-Waste","Bin":"Red"},
"Laptop Adapter": {"Item":"E-Waste","Bin":"Red"},
"Laptop Motherboard": {"Item":"E-Waste","Bin":"Red"},
"Desktop CPU": {"Item":"E-Waste","Bin":"Red"},
"Computer Monitor": {"Item":"E-Waste","Bin":"Red"},
"LCD Screen": {"Item":"E-Waste","Bin":"Red"},
"LED Screen": {"Item":"E-Waste","Bin":"Red"},
"Broken Keyboard": {"Item":"E-Waste","Bin":"Red"},
"Broken Mouse": {"Item":"E-Waste","Bin":"Red"},
"UPS": {"Item":"E-Waste","Bin":"Red"},
"Inverter": {"Item":"E-Waste","Bin":"Red"},
"Inverter Battery": {"Item":"Hazardous","Bin":"Red"},
"Stabilizer": {"Item":"E-Waste","Bin":"Red"},
"Electric Switch": {"Item":"E-Waste","Bin":"Red"},
"Electric Socket": {"Item":"E-Waste","Bin":"Red"},
"Circuit Board": {"Item":"E-Waste","Bin":"Red"},
"Printed Circuit Board": {"Item":"E-Waste","Bin":"Red"},
"Electronic Scrap": {"Item":"E-Waste","Bin":"Red"},

# ---------- PERSONAL CARE / COSMETIC ----------
"Used Razor": {"Item":"Hazardous","Bin":"Red"},
"Disposable Razor": {"Item":"Hazardous","Bin":"Red"},
"Shaving Blade": {"Item":"Hazardous","Bin":"Red"},
"Hair Removal Blade": {"Item":"Hazardous","Bin":"Red"},
"Hair Straightener": {"Item":"E-Waste","Bin":"Red"},
"Hair Dryer": {"Item":"E-Waste","Bin":"Red"},
"Electric Trimmer": {"Item":"E-Waste","Bin":"Red"},
"Electric Shaver": {"Item":"E-Waste","Bin":"Red"},
"Electric Toothbrush": {"Item":"E-Waste","Bin":"Red"},
"Cosmetic Applicator Used": {"Item":"Sanitary","Bin":"Red"},
"Makeup Sponge Used": {"Item":"Sanitary","Bin":"Red"},
"Used Cotton Ball": {"Item":"Sanitary","Bin":"Red"},
"Used Cotton Swab": {"Item":"Sanitary","Bin":"Red"},
"Contact Lens": {"Item":"Sanitary","Bin":"Red"},
"Contact Lens Case": {"Item":"Sanitary","Bin":"Red"},

# ---------- MEDICAL & HEALTH ----------
"Blood-Stained Cotton": {"Item":"Sanitary","Bin":"Red"},
"Blood-Stained Cloth": {"Item":"Sanitary","Bin":"Red"},
"Used First Aid Kit": {"Item":"Hazardous","Bin":"Red"},
"Expired Ointment": {"Item":"Hazardous","Bin":"Red"},
"Expired Syrup": {"Item":"Hazardous","Bin":"Red"},
"Medical Packaging Contaminated": {"Item":"Hazardous","Bin":"Red"},
"Used Test Tube": {"Item":"Hazardous","Bin":"Red"},
"IV Tube": {"Item":"Hazardous","Bin":"Red"},
"Drip Set": {"Item":"Hazardous","Bin":"Red"},
"Used Glucometer Strip": {"Item":"Hazardous","Bin":"Red"},
"Glucometer Device": {"Item":"E-Waste","Bin":"Red"},
"Pulse Oximeter": {"Item":"E-Waste","Bin":"Red"},
"Blood Pressure Monitor": {"Item":"E-Waste","Bin":"Red"},
"Nebulizer": {"Item":"E-Waste","Bin":"Red"},
"Nebulizer Mask": {"Item":"Hazardous","Bin":"Red"},

# ---------- HOUSEHOLD HAZARDOUS ----------
"Used Mosquito Coil": {"Item":"Hazardous","Bin":"Red"},
"Mosquito Coil Ash": {"Item":"Hazardous","Bin":"Red"},
"Mosquito Liquid Refill": {"Item":"Hazardous","Bin":"Red"},
"Room Freshener Can": {"Item":"Hazardous","Bin":"Red"},
"Aerosol Spray Can": {"Item":"Hazardous","Bin":"Red"},
"Gas Lighter": {"Item":"Hazardous","Bin":"Red"},
"Matchbox": {"Item":"Hazardous","Bin":"Red"},
"Firecracker Waste": {"Item":"Hazardous","Bin":"Red"},
"Firework Residue": {"Item":"Hazardous","Bin":"Red"},
"Broken Thermometer Mercury": {"Item":"Hazardous","Bin":"Red"},

# ---------- AUTOMOTIVE / TOOLS ----------
"Car Battery": {"Item":"Hazardous","Bin":"Red"},
"Bike Battery": {"Item":"Hazardous","Bin":"Red"},
"Vehicle Fuse": {"Item":"Hazardous","Bin":"Red"},
"Used Engine Oil Container": {"Item":"Hazardous","Bin":"Red"},
"Grease Container": {"Item":"Hazardous","Bin":"Red"},
"Lubricant Spray": {"Item":"Hazardous","Bin":"Red"},
"Paint Thinner": {"Item":"Hazardous","Bin":"Red"},
"Rust Remover": {"Item":"Hazardous","Bin":"Red"},
"Tool Battery": {"Item":"Hazardous","Bin":"Red"},
"Electric Drill": {"Item":"E-Waste","Bin":"Red"},

# ---------- MISCELLANEOUS RED ----------
"Broken Charger Pin": {"Item":"E-Waste","Bin":"Red"},
"Damaged Power Strip": {"Item":"E-Waste","Bin":"Red"},
"Burnt Electronic Component": {"Item":"E-Waste","Bin":"Red"},
"Broken PCB Piece": {"Item":"E-Waste","Bin":"Red"},
"Electronic Wire Scrap": {"Item":"E-Waste","Bin":"Red"},
"Sharp Metal Scrap": {"Item":"Hazardous","Bin":"Red"},
"Broken Blade": {"Item":"Hazardous","Bin":"Red"},
"Sharp Object Waste": {"Item":"Hazardous","Bin":"Red"},
"Contaminated Plastic Waste": {"Item":"Hazardous","Bin":"Red"},
"Household Hazardous Waste": {"Item":"Hazardous","Bin":"Red"}

}




